version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    labels:
      - dependencies
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
    groups:
      npm:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    versioning-strategy: increase
    target-branch: v3
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
    groups:
      npm:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'nhsuk-frontend'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-major']
