version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
    groups:
      npm:
        patterns: ['*']
    ignore:
      - dependency-name: '@types/node'
        versions: ['>=22.0.0']
